### ISSUE TITLE
Multiple objects in post body

### ISSUE THREAD

**Issue by andreaTP** [unicredit/sbt-swagger-codegen#1]
Client doesn't support multiple objects in body.

**Comment by giux78** [comment]
It seems we have the same problem. Posting simple but nested object seems not to work. The exception is raised because in the model package some classes are missing.

**Comment by fralken** [comment]
Actually  [Swagger 2.0 specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object) says that there can only be one body parameter.

> Body - The payload that's appended to the HTTP request. Since there can only be one payload, there can only be one body parameter. The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only.

The bug is that the code generator doesn't check this and generates wrong code: server code compiles but is wrong, client code doesn't compile at all.

**Comment by fralken** [comment]
fixed in version 0.0.11
