### ISSUE TITLE
PUT method without body parameter generates bad client code

### ISSUE THREAD

**Issue by miron89** [unicredit/sbt-swagger-codegen#64]
I have Scala Play application with the following route:

`PUT        /scalator/api/tasks/:id/toggle    controllers.TasksController.toggleTask(id: Int)`

my yaml representation for that path looks like this:

<img width="310" alt="screen shot 2018-02-05 at 11 38 13" src="https://user-images.githubusercontent.com/26618996/35797684-1f8c565a-0a69-11e8-80ee-ddbf5e1cbda7.png">

when I try to generate the client code I get the following compilation error:

<img width="1068" alt="screen shot 2018-02-05 at 11 39 29" src="https://user-images.githubusercontent.com/26618996/35797761-70c43b0a-0a69-11e8-93e4-8276e77de97c.png">

I managed to fix the issue by editing the swagger client generated code:

1. first solution - put() -> put(() : Unit)
2. the second option is to extend the DefaultBodyWritables class as suggested

both solutions are temporary only since the the file will be generated again with the same error next time I will build the project.

as a necessity i've changed the method from PUT to GET in order to make it work...

Please advise how to handle this issue without workarounds
Thanks

**Comment by fralken** [comment]
The problem is not the inline parameter, but the missing body. PUT operations should have a body.
Now we have to decide which strategy to use in case of missing body in PUT and POST operations: either to throw an exception if there is no body parameter in the swagger specification, or to generate an empty content body.
Indeed it is not correct to generate code that does not compile.

**Comment by fralken** [comment]
Now it requires one body parameter for POST an PUT methods
