### ISSUE TITLE
Duplicate case classes generated

### ISSUE THREAD

**Issue by rethab** [unicredit/sbt-swagger-codegen#74]
I tried the new 0.0.12-SNAPSHOT on one project and it seems to generate case classes twice. Unfortunately, I cannot share the schema, but I'll try to give as much information as possible.

We have two yaml files:
- api.yaml
- api-models.yaml

api.yaml contains something like:
```yaml
responses:
  200:
    schema:
      $ref: './api-models.yaml/#/definitions/MyResponse'
```

api-models.yaml contains something like this:
```yaml
MyResponse:
  type: object
  required:
    - id
  properties:
    id:
      type: string
    meta:
      $ref: '#/definitions/Meta'
Meta:
  type: object
  required:
    - notifications
  properties:
    notifications:
      type: array
      items:
        $ref: '#/definitions/Notification'
```

This generates a scala file Model.scala:
```scala
case class MyResponse(id: String, meta: Option[Meta] = None)
case class Meta(notifications: Seq[Notification])
case class MyResponse(id: String, meta: Option[Meta] = None)
case class Meta(notifications: Seq[Notification])
```

If necessary, I can try to provide a smaller reproducing sample, but this might already be enough to identify the issue.

**Comment by fralken** [comment]
Hello, this is because the plugin parses all yaml files it finds in the swagger folder. Since your models are in a separate file, they are parsed both when reading route definitions (because they are referenced there) and again when reading the model definitions file.

For now, as a workaround, you can do one of the following:

1. put the model definitions file in a different folder (not the default swagger folder, it can be a subfolder of this one), or
2. put model definitions in the same file of route definitions
 

I'm going to improve the logic of how yaml file are parsed.

**Comment by rethab** [comment]
Hi @fralken thanks for the quick response. Since you are going to improve this and I just wanted to try the new version, no workaround is necessary for now.

Thanks!

**Comment by fralken** [comment]
@rethab now it should manage multiple swagger files, where model definitions can be in a separate file.
Generated package is now by default `swagger.codegen.<name of the swagger file (lowercase w/o extension)>` to avoid possible name clashes.

**Comment by rethab** [comment]
hi @fralken thanks a lot for the update! I noticed one other small issue: Some of our projects use versions in filenames. I noticed you are generating package names based on file names (https://github.com/unicredit/sbt-swagger-codegen/commit/bb09886d85229940f2dfc2b5de4981cf159b65a2#diff-3d317ec54123c5050a8bc5e370b056f2R342) which leads to invalid package names.

For example, we have one file named `swagger.1.2.x.json`, which leads to a package with those numbers. I think with version `0.0.11`, it was taking the package name from the setting `swaggerCodeGenPackage`

**Comment by fralken** [comment]
We can have more swagger files with definitions and models sharing names, so we have to separate namespaces of each file in some way. An idea was to append the file name to the package defined in `swaggerCodeGenPackage`. The file name must be cleaned appropriately.

Another option could be to permit only one swagger file for definitions (and optionally a separate file for models, referenced by the definitions). There would be a setting containing the filename.

**Comment by rethab** [comment]
if you want to change how package names are generated with the new version, might it be an option to quote them? for us, it would obviously be most convenient if it worked like before ;-)

**Comment by fralken** [comment]
Now I "backtick" package names and class names when needed. We can lose something in readability but it works.

Isolating swagger definitions in sub packages becomes necessary since you can have name clashes among different swagger files, so you cannot put everything in the single package defined in `swaggerCodeGenPackage`.

**Comment by mfirry** [comment]
@fralken can we close this?
